import type { Metadata } from "next";
import "./globals.css";
import ScreenSizeIndicator from "@/components/ScreenSizeIndicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <ScreenSizeIndicator />
      </body>
    </html>
  );
}
